<?php
namespace KG_Core\Blocks;

class EmbedBlock {
    
    public function __construct() {
        add_action('init', [$this, 'register_blocks']);
        add_action('enqueue_block_editor_assets', [$this, 'enqueue_editor_assets']);
        add_action('wp_ajax_kg_block_search_content', [$this, 'ajax_search_content']);
    }
    
    /**
     * Register all embed blocks
     */
    public function register_blocks() {
        // Register the embed block
        register_block_type(
            KG_CORE_PATH . 'blocks/build/kg-embed'
        );
    }
    
    /**
     * Enqueue block editor assets
     */
    public function enqueue_editor_assets() {
        // The script handle is auto-generated by WordPress from the block name
        // Format: {namespace}-{block-name}-editor-script
        // For kg-core/embed it becomes: kg-core-embed-editor-script
        $script_handle = 'kg-core-embed-editor-script';
        
        // Localize script with AJAX URL and nonce
        wp_localize_script($script_handle, 'kgBlockEmbed', [
            'ajaxUrl' => admin_url('admin-ajax.php'),
            'nonce' => wp_create_nonce('kg_block_embed_nonce'),
        ]);
    }
    
    /**
     * AJAX handler for searching content
     */
    public function ajax_search_content() {
        // Verify nonce
        if (!isset($_POST['nonce']) || !wp_verify_nonce($_POST['nonce'], 'kg_block_embed_nonce')) {
            wp_send_json_error(['message' => __('Security check failed', 'kg-core')]);
            return;
        }
        
        $type = isset($_POST['type']) ? sanitize_text_field($_POST['type']) : 'recipe';
        $search = isset($_POST['search']) ? sanitize_text_field($_POST['search']) : '';
        
        $allowed_types = ['recipe', 'ingredient', 'tool', 'post'];
        
        if (!in_array($type, $allowed_types)) {
            wp_send_json_error(['message' => __('Invalid content type', 'kg-core')]);
            return;
        }
        
        // Query args
        $args = [
            'post_type' => $type,
            'post_status' => 'publish',
            'posts_per_page' => 20,
            'orderby' => 'title',
            'order' => 'ASC',
        ];
        
        if (!empty($search)) {
            $args['s'] = $search;
        }
        
        $query = new \WP_Query($args);
        $results = [];
        
        if ($query->have_posts()) {
            while ($query->have_posts()) {
                $query->the_post();
                $post_id = get_the_ID();
                
                $item = [
                    'id' => $post_id,
                    'title' => html_entity_decode(get_the_title(), ENT_QUOTES | ENT_HTML5, 'UTF-8'),
                    'image' => $this->get_thumbnail_url($post_id),
                    'meta' => $this->get_meta_info($post_id, $type),
                    'icon' => $this->get_type_icon($type),
                ];
                
                $results[] = $item;
            }
            wp_reset_postdata();
        }
        
        wp_send_json_success(['items' => $results]);
    }
    
    /**
     * Get thumbnail URL
     */
    private function get_thumbnail_url($post_id) {
        $thumbnail_id = get_post_thumbnail_id($post_id);
        
        if ($thumbnail_id) {
            return wp_get_attachment_image_url($thumbnail_id, 'thumbnail');
        }
        
        return '';
    }
    
    /**
     * Get meta information based on content type
     */
    private function get_meta_info($post_id, $type) {
        $meta = '';
        
        switch ($type) {
            case 'recipe':
                $prep_time = get_post_meta($post_id, '_kg_prep_time', true);
                $age_groups = wp_get_post_terms($post_id, 'age-group');
                
                $parts = [];
                if ($prep_time) {
                    $parts[] = $prep_time;
                }
                if (!empty($age_groups)) {
                    $parts[] = html_entity_decode($age_groups[0]->name, ENT_QUOTES | ENT_HTML5, 'UTF-8');
                }
                $meta = implode(' • ', $parts);
                break;
                
            case 'ingredient':
                $start_age = get_post_meta($post_id, '_kg_start_age', true);
                if ($start_age) {
                    $meta = $start_age;
                }
                break;
                
            case 'tool':
                $tool_type = get_post_meta($post_id, '_kg_tool_type', true);
                if ($tool_type) {
                    $meta = $tool_type;
                }
                break;
                
            case 'post':
                $categories = get_the_category($post_id);
                if (!empty($categories)) {
                    $meta = html_entity_decode($categories[0]->name, ENT_QUOTES | ENT_HTML5, 'UTF-8');
                }
                break;
        }
        
        return $meta;
    }
    
    /**
     * Get icon for content type
     */
    private function get_type_icon($type) {
        $icons = [
            'recipe' => 'dashicons-food',
            'ingredient' => 'dashicons-carrot',
            'tool' => 'dashicons-admin-tools',
            'post' => 'dashicons-format-aside',
        ];
        
        return isset($icons[$type]) ? $icons[$type] : 'dashicons-admin-post';
    }
}
